package cn.ll.mapper;

import cn.ll.domain.Ebook;
import cn.ll.domain.EbookExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EbookMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ebook
     *
     * @mbg.generated Thu May 26 14:55:49 CST 2022
     */
    long countByExample(EbookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ebook
     *
     * @mbg.generated Thu May 26 14:55:49 CST 2022
     */
    int deleteByExample(EbookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ebook
     *
     * @mbg.generated Thu May 26 14:55:49 CST 2022
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ebook
     *
     * @mbg.generated Thu May 26 14:55:49 CST 2022
     */
    int insert(Ebook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ebook
     *
     * @mbg.generated Thu May 26 14:55:49 CST 2022
     */
    int insertSelective(Ebook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ebook
     *
     * @mbg.generated Thu May 26 14:55:49 CST 2022
     */
    List<Ebook> selectByExample(EbookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ebook
     *
     * @mbg.generated Thu May 26 14:55:49 CST 2022
     */
    Ebook selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ebook
     *
     * @mbg.generated Thu May 26 14:55:49 CST 2022
     */
    int updateByExampleSelective(@Param("record") Ebook record, @Param("example") EbookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ebook
     *
     * @mbg.generated Thu May 26 14:55:49 CST 2022
     */
    int updateByExample(@Param("record") Ebook record, @Param("example") EbookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ebook
     *
     * @mbg.generated Thu May 26 14:55:49 CST 2022
     */
    int updateByPrimaryKeySelective(Ebook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ebook
     *
     * @mbg.generated Thu May 26 14:55:49 CST 2022
     */
    int updateByPrimaryKey(Ebook record);
}